export default {
   CARD_OFFSET_TOP:30,
   CARD_WIDTH:80,
   CARD_HEIGHT:115,
   CARD_BACK:'/cards/back.png',
   GAME_BOARD:'board',
    
   WASTE:'WASTE',
   STOCK:'STOCK',
    
   TABLEAU_ONE:'TABLEAU_ONE',
   TABLEAU_TWO:'TABLEAU_TWO',
   TABLEAU_THREE:'TABLEAU_THREE',
   TABLEAU_FOUR:'TABLEAU_FOUR',
   TABLEAU_FIVE:'TABLEAU_FIVE',
   TABLEAU_SIX:'TABLEAU_SIX',
    
   FOUNDATION_PILE_HEARTS:'FOUNDATION_PILE_HEARTS',
   FOUNDATION_PILE_SPADES:'FOUNDATION_PILE_SPADES',
   FOUNDATION_PILE_DIAMONDS:'FOUNDATION_PILE_DIAMONDS',
   FOUNDATION_PILE_CLOVERS:'FOUNDATION_PILE_CLOVERS',
   FOUNDATION_PILE_ORDER:["A","2","3","4","5","6","7","8","9","0","J","Q","K"]
};